Myecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import  settings
from django.conf.urls.static import  static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payments.urls')),
    path('products/', include('products.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/urls.py

from django.urls import path,include
from . import views
app_name='account'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('profile/<str:username>',views.user_profile,name='profile'),
    # path('search_user/<str:keyword>',views.search_user,name='search_user'),
]

cart/urls.py
#
from django.urls import path
from . import views
app_name='cart'
urlpatterns = [
    path('add/<int:id>/', views.add,name='add'),
    path('display_cart/', views.display_cart,name='display_cart'),
    path('update_number/<int:id>/', views.update_number,name='update_number'),
    path('remove/<int:id>/', views.remove_from_cart,name='remove_from_cart'),
]

cart/models.py
from django.db import models
from products.models import products
from django.contrib.auth.models import User

# Create your models here.

class cart_item(models.Model):
    myproduct=models.ForeignKey(products,on_delete=models.CASCADE,related_name='items')
    number=models.IntegerField(default=1)
    total=models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.myproduct.name


class cart(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    cart_items = models.ManyToManyField('cart_item',related_name='carts',blank=True)
    total=models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.user.username


cart/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse
from products.models import products
from .models import cart, cart_item
from django.contrib.auth.decorators import login_required


@login_required
def add(request, id):
    get_product = get_object_or_404(products, id=id)
    user = request.user
    mycart_item = cart_item.objects.create(myproduct=get_product)
    get_cart, created = cart.objects.get_or_create(user=user)
    print(mycart_item)
    print(get_cart.cart_items.all())

    x = get_cart.cart_items.filter(myproduct=mycart_item.myproduct)
    # if mycart_item not in get_cart.cart_items.all():
    if not x.exists():
        get_cart.cart_items.add(mycart_item)
    total = 0
    for item in get_cart.cart_items.all():
        item.total = item.myproduct.price * item.number
        item.save()
        total += item.myproduct.price * item.number

    get_cart.total = total
    get_cart.save()
    return HttpResponseRedirect(reverse("home"))


def display_cart(request):
    get_cart = get_object_or_404(cart, user=request.user)
    return render(request, "cart.html", {'cart': get_cart})


def remove_from_cart(request, id):
    user = request.user
    mycart = cart.objects.get(user=user)
    mycart_item = get_object_or_404(cart_item, id=id)
    mycart.cart_items.remove(mycart_item)
    # mycart.total-=mycart_item.product.price
    mycart.total -= mycart_item.total
    mycart.save()
    return HttpResponseRedirect(reverse('cart:display_cart'))


def update_number(request, id):
    mycart_item = get_object_or_404(cart_item, id=id)
    mycart_item.number = request.POST['number']
    mycart_item.save()
    mycart = get_object_or_404(cart, user=request.user)
    total = 0
    for item in mycart.cart_items.all():
        item.total = item.myproduct.price * item.number
        item.save()
        total += item.myproduct.price * item.number
    mycart.total = total
    mycart.save()

    print(mycart_item.number)
    print(id)
    print(request.POST['number'])
    return HttpResponseRedirect(reverse('cart:display_cart'))

#
# def charge(request):
#     print('charge==========================')
#     get_cart, created = cart.objects.get_or_create(user=request.user)
#     for item in get_cart:
#         request.user.profile.orders.add(item.myproduct)
#         request.user.profile.save()
#     return  render(request, 'charge.html')

templates/basepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <!-- custom css -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/util.css' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap" rel="stylesheet">

    <title>
        {% block title %}

        {% endblock %}
    </title>

</head>

<body>
<!-- header -->
<!-- <section id="header-section"> -->
<header class="container">
    <div class="row flex-nowrap justify-content-around align-items-center py-3">

        <a class="col-sm-2 col-md-2 col-lg-2" href="{% url 'home' %}"> <img
                src="{% static 'img/The_Fresh_Market_logo.svg' %}" width="75" height="75"></a>

        <form class="col-sm-6 col-lg-6 form-inline my-2 my-lg-0 " method="get" action="{%url 'search' %}">
            <input class="form-control mr-sm-2" type="search" name="keyword" placeholder="Search"
                   aria-label="Search">
            <!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->

        </form>


        {% if request.user.is_authenticated %}

        <!--                <a class="col-sm-12 col-md-3 col-lg-1 btn btn-md btn-outline-success my_user_name my-auto  "-->
        <!--                   href="{% url 'account:login' %}">{{ request.user.username }}</a>-->

            {% if request.user.profile.image %}
    
            <a class="btn col-sm-2   col-lg-1 egoreis " href="{% url 'account:profile'  request.user.username %} ">
                <img class="thumbnail circular_image"
                     width="40"
                     height="40"
                     src="{{ request.user.profile.image.url }}"></a>
    
            {% else %}
    
            <a class="btn col-sm-2  col-lg-1 egoreis " href="{% url 'account:profile'  request.user.username %}"><img
                    class="thumbnail circular_image"
                    width="40"
                    height="40"
                    src="{% static 'img/user.png' %}"></a>
            {% endif %}
        <a class="btn col-sm-2  col-lg-1 egoreis  my_logout  my-auto mr-0" href="{% url 'account:logout' %}">Logout</a>

        {% else %}

        <div class="col-sm-2 col-md-4 col-lg-3 ">
            <a class="btn btn-md col-sm-12 col-md-3   my-auto  egoreis login_btn"
               href="{% url 'account:login' %}">Login</a>
            <a class="btn btn-md  col-sm-12 col-md-3   my-auto egoreis  reg_btn"
               href="{% url 'account:register' %}">Register</a>
        </div>
        {% endif%}
        <!--        <a href="{% url 'account:register' %}">-->
        <a href="{%  url 'cart:display_cart' %}"> <div class=" col-sm-2   col-md-2 col-lg-1">
                    <span id="reduce" class="fa-stack fa-2x has-badge mr-2 " data-count="{{ request.user.cart.cart_items.all | length }}">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                </span>
        </div>
            </a>
    </div>

</header>

<div class="container-fluid bg-dark">
    <div class="container  ">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2">
            <a class="navbar-brand" href="{% url 'home' %}">
                All Categories</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-auto">

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'category' 'electronics' %}">
                            Electronics
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'category' 'mobiles' %}">
                            Mobiles
                        </a>
                    </li>
                    <li class="nav-item">

                        <a class="nav-link" href="{% url 'category' 'fashion'  %}">
                            Fashion
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'category' 'home'  %}">
                            Home
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'category' 'beauty & health'  %}">
                            Beauty & Health
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'category' 'baby'  %}">
                            Baby
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'category' 'our market'  %}">
                            Our Market
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'category' 'daily deals'  %}">
                            Daily Deals
                        </a>
                    </li>
                </ul>
                <!--    <form class="form-inline my-2 my-lg-0">-->
                <!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
                <!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
                <!--    </form>-->
            </div>
        </nav>
    </div>
</div>
<div>

    {% block content %}

    {% endblock %}

</div>
<!-- footer -->

<footer>
    <!-- contact us  -->
    <!-- Categories -->
    <!-- social media -->
    <div class="row m-0 bg-dark py-5">

        <div class="col-sm-12 col-md-6 col-lg-3 my-3">
            <ul class="text-light  text-center  align-items-center justify-content-center">
                <li class="text-capitalize font-weight-bold pb-3"><a  class="text-light" href="{% url 'category' 'electronics' %}"> Electronics </a></li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=tv"  > Led Screen </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=air condition"  > Air Contion </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=dishwasher"  > DishWasher </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=fridge"  > Fridge </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=tv" > TV </a> </li>
            </ul>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3  my-3">
            <ul class="text-light text-center">

                <li class="text-capitalize font-weight-bold pb-3"><a  class="text-light"   href="{% url 'category' 'mobiles' %}"> Mobiles </a></li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=samsung"> Samsung </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=huawi"> Huawi </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=iphone"> Iphone </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=htc"> HTC </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=oppo"> OPPO </a> </li>

            </ul>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-3  my-3">
            <ul class="text-light text-center">
                <li class="text-capitalize font-weight-bold  pb-3"><a class="text-light"   href="{% url 'category' 'beauty & health' %}"> Beauty & Health </a></li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=tools_accessories"> Tools & Accessories </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=personalcare"> Personal Care </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=makeup"> Make-Up </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=haircare"> HairCare </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=skincare"> SkinCare </a> </li>
            </ul>
        </div>

        <div class="col-sm-12 col-md-6 col-lg-3 my-3">
            <ul class="text-light text-center">
                <li class="text-capitalize font-weight-bold pb-3"><a  class="text-light"   href="{% url 'category' 'fashion' %}"> Fashion </a></li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=shiftdress"> Shift Dress </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=bodycondress"> Bodycon Dress </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=alinedress"> A-Line Dress </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=wrapdress"> Wrap Dress </a> </li>
                <li> <a class="text-light"  href="{% url 'search' %}?keyword=halterdress"> Halter Dress </a> </li>
            </ul>
        </div>

    </div>
    <div class="row m-0 bg-dark py-5">
        <div class="col-md-12 ">
            <div class="footer-social">
                <ul class="list-unstyled row align-items-center justify-content-center">
                    <li><a class="mx-2 wrap-row fadeInUp " href="#"><i class="fa fa-facebook-f" aria-hidden="true"></i></a>
                    </li>
                    <li><a class="mx-2 wrap-row fadeInDown" href="#"><i class="fa fa-twitter"
                                                                        aria-hidden="true"></i></a></li>
                    <li><a class="mx-2 wrap-row fadeInUp" href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>
                    </li>
                    <li><a class="mx-2 wrap-row fadeInDown" href="#"><i class="fa fa-linkedin"
                                                                        aria-hidden="true"></i></a></li>
                    <li><a class="mx-2 wrap-row fadeInUp" href="#"><i class="fa fa-instagram"
                                                                      aria-hidden="true"></i></a></li>
                    <li><a class="mx-2 wrap-row fadeInDown" href="#"><i class="fa fa-envelope"
                                                                        aria-hidden="true"></i></a></li>
                </ul>
            </div>
            <p class="company-about fadeIn row text-center m-2 text-light justify-content-center"> © {% now 'Y' %} ITI.
                Made With Love By <a class="ml-3" href="#"> ITI Team </a></p>
        </div>
    </div>


</footer>
<!-- footer -->


<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/main.js' %}" charset="utf-8"></script>
</body>

</html>

templates/caresol.html

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Swiper demo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

  <!-- Link Swiper's CSS -->
  <link rel="stylesheet" href="../package/css/swiper.min.css">

  <!-- Demo styles -->
  <style>
    html, body {
      position: relative;
      height: 100%;
    }
    body {
      background: #eee;
      font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
      font-size: 14px;
      color:#000;
      margin: 0;
      padding: 0;
    }
    .swiper-container {
      width: 100%;
      height: 100%;
    }
    .swiper-slide {
      text-align: center;
      font-size: 18px;
      background: #fff;

      /* Center slide text vertically */
      display: -webkit-box;
      display: -ms-flexbox;
      display: -webkit-flex;
      display: flex;
      -webkit-box-pack: center;
      -ms-flex-pack: center;
      -webkit-justify-content: center;
      justify-content: center;
      -webkit-box-align: center;
      -ms-flex-align: center;
      -webkit-align-items: center;
      align-items: center;
    }
  </style>
</head>
<body>
  <!-- Swiper -->
  <div class="swiper-container">
    <div class="swiper-wrapper">
      <div class="swiper-slide">Slide 1</div>
      <div class="swiper-slide">Slide 2</div>
      <div class="swiper-slide">Slide 3</div>
      <div class="swiper-slide">Slide 4</div>
      <div class="swiper-slide">Slide 5</div>
      <div class="swiper-slide">Slide 6</div>
      <div class="swiper-slide">Slide 7</div>
      <div class="swiper-slide">Slide 8</div>
      <div class="swiper-slide">Slide 9</div>
      <div class="swiper-slide">Slide 10</div>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Arrows -->
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
  </div>

  <!-- Swiper JS -->
  <script src="../package/js/swiper.min.js"></script>

  <!-- Initialize Swiper -->
  <script>
    var swiper = new Swiper('.swiper-container', {
      slidesPerView: 3,
      spaceBetween: 30,
      slidesPerGroup: 3,
      loop: true,
      loopFillGroupWithBlank: true,
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
  </script>
</body>
</html>

templates/cart.html
{% extends 'basepage.html' %}
{% load static %}

{% block title %}
Cart
{% endblock %}

{% block content %}
</header>
<!-- </section> -->
<link rel="stylesheet" href="{% static 'css/cart.css' %}">
<div class="container-fluid product_bg py-2">
    <div id="products-container" class="container">
        <section id="main-section" class="ml-auto">

            {% if cart.cart_items.all %}

            <div class="container my-4">
                <div class="row">
                    <div class="col-12">
                        <div>
                            <table class="table table-striped">
                                <thead>
                                <tr scope="row">
                                    <th scope="col" class="font_limit text-light"></th>
                                    <th scope="col">Product</th>
                                    <th scope="col">Available</th>

                                    <th scope="col" class="text-center">Quantity</th>
                                    <th scope="col"></th>
                                    <th scope="col" class="text-right">Price</th>

                                    <th scope="col"></th>
                                </tr>
                                </thead>
                                <tbody>
                                {%for cart_item in cart.cart_items.all%}

                                <tr scope="row" class="justify-content-center ">
                                    <td><img src="{{ cart_item.myproduct.image.url }} " width="50" height="50"/></td>
                                    <td class="success">{{cart_item.myproduct.name}}</td>
                                    <td>In stock</td>
                                    <form action="{%url 'cart:update_number' cart_item.id %}" method="POST">
                                        {%csrf_token%}
                                        <td>
                                            <input class="form-control" type="text" name="number"
                                                   value={{cart_item.number}}>

                                        </td>

                                        <td>
                                            <button type="submit" class="btn btn-sm btn-success"><i
                                                    class="fa fa-save"></i></button>

                                        </td>
                                    </form>
                                    <td class="text-right">{{cart_item.total}} $</td>
                                    <form action="{% url 'cart:remove_from_cart' cart_item.id%}" method="POST">
                                        {%csrf_token%}
                                        <td class="text-right">
                                            <button type="submit" class="btn btn-sm btn-danger"><i
                                                    class="fa fa-trash"></i></button>
                                        </td>
                                    </form>
                                </tr>
                                {%endfor%}

                                <tr>

                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td><strong>Total</strong></td>
                                    <td class="text-right"><strong>{{cart.total}} $</strong></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>

                    <div class="col mb-2">
                        <div class="row">
                            <div class="col-sm-12  text-center justify-content-center mx-auto">

                                <!--                    <a type="submit" href="{%url 'home' %}" class="btn  bg-dark text-light">Continue Shopping</a>-->

                            </div>
                            <div class="col-sm-12 ">
                                <form action="{% url 'charge' %}" method="post"
                                      class=" text-center justify-content-center mx-auto">
                                    {% csrf_token %}
                                    <script src="https://checkout.stripe.com/checkout.js"
                                            class="stripe-button"
                                            data-key="pk_test_oUBwpwP3y25hbJbQhDJZYv3K00W6WF7sVs"
                                            data-description="A Django Charge"
                                            data-amount="{{cart.total}}"
                                            data-locale="auto"></script>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% else %}
            <div class="row">
                <div class=" mx-auto my-5 py-3">
                    <form action="{% url 'home' %}" method="POST">
                        {%csrf_token%}

                        <button type="submit" class="btn btn-sm btn-success font-weight-bold">
                            <i class="fa-check-double"></i> Continue Shopping
                        </button>
                        <h4 class="my-2 py-2">You didn't Purchase Any products Yet . </h4>
                    </form>

                </div>
            </div>
            {% endif %}
        </section>
    </div>
</div>
<!-- products section -->
{% endblock %}

templates/display_cart.html

{%extends 'base.html'%}
{%load static%}
{%block content%}


<link rel="stylesheet" href="{%static 'cart.css' %}">

<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">E-COMMERCE CART</h1>
     </div>
</section>


<div class="container mb-4">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col"> </th>
                            <th scope="col">Product</th>
                            <th scope="col">Available</th>
                            
                            <th scope="col" class="text-center">Quantity</th>
                            <th></th>
                            <th scope="col" class="text-right">Price</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        {%for cart_item in cart.cart_items.all%}
                        
                        <tr>
                            <td><img src="https://dummyimage.com/50x50/55595c/fff" /> </td>
                            <td>{{cart_item.product.title}}</td>
                            <td>In stock</td>
                            <form action="{%url 'cart:update_number' cart_item.id %}" method="POST">
                                {%csrf_token%}
                            <td>
                                <input class="form-control" width="50" type="text" name="number" value={{cart_item.number}} />
 
                            </td>
                          
                            <td> 
                                <button type="submit" class="btn btn-sm btn-danger"><i class="fas fa-save"></i> </button>
                               
                            </td>
                        </form>
                            <td class="text-right">{{cart_item.total}} €</td>
                            <form action="{% url 'cart:remove_from_cart' cart_item.id%}" method="POST">
                                {%csrf_token%}
                            <td class="text-right"><button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> </button> </td>
                            </form>
                        </tr>
                        {%endfor%}

                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td class="text-right"></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><strong>Total</strong></td>
                            <td class="text-right"><strong>{{cart.total}} €</strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col mb-2">
            <div class="row">
                <div class="col-sm-12  col-md-6">
                  
                    <a type="submit" href="{%url 'products' %}" class="btn btn-block btn-light">Continue Shopping</a>
                
                </div>
                <div class="col-sm-12 col-md-6 text-right">
                    <button class="btn btn-lg btn-block btn-success text-uppercase">Checkout</button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Footer -->
<footer class="text-light">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-lg-4 col-xl-3">
                <h5>About</h5>
                <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                <p class="mb-0">
                    Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.
                </p>
            </div>

       

            <div class="col-md-4 col-lg-3 col-xl-3">
                <h5>Contact</h5>
                <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                <ul class="list-unstyled">
                    <li><i class="fa fa-home mr-2"></i> My company</li>
                    <li><i class="fa fa-envelope mr-2"></i> email@example.com</li>
                    <li><i class="fa fa-phone mr-2"></i> + 33 12 14 15 16</li>
                    <li><i class="fa fa-print mr-2"></i> + 33 12 14 15 16</li>
                </ul>
            </div>
            <div class="col-12 copyright mt-3">
                <p class="float-left">
                    <a href="#">Back to top</a>
                </p>
            </div>
        </div>
    </div>
</footer>
{%endblock%}

templates/login.html
{% extends 'basepage.html' %}
{% load static %}

{% block title %}
Login
{% endblock %}

{% block content %}
</header>
<!-- </section> -->

<section  >
         	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
<!--				<div class="login100-pic js-tilt" data-tilt>-->
<!--					<img src="{% static  'img/img-01.png' %}" alt="IMG">-->
<!--				</div>-->

				<form class="login100-form validate-form" method="post" action=".">
					            {% csrf_token %}
					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="username" placeholder="Email">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="material-icons">contact_mail</i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="material-icons">lock</i>
						</span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center mx-2">
						<a class="txt2" href="{% url 'account:register' %}">
							Create your Account
							<i class="material-icons mt-2 text-center" aria-hidden="true">arrow_right_alt</i>
						</a>
					</div>

				</form>
			</div>
 	</div>
    </div>
</section>
<!-- products section -->
{% endblock %}